### ISSUE TITLE
Tutorial / Website Enhancements after 2.6.0 Release

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML-Website#163]
Moving open points from #161 to here.

- [x] Add mention of SFML CMake Template see #160 and [potential implementation](https://github.com/ChrisThrasher/SFML-Website/commit/668fdfed77ec30084e611a4f9095aa7635bf33a8)
- [x] Update CMake tutorial, for using GNU Install Dirs (especially macOS), see https://github.com/SFML/SFML/issues/1563#issuecomment-466982693
- [x] Updating the french translation for this change https://github.com/SFML/SFML-Website/pull/161/commits/6570978b2d754dbe76f2dbed93e75e5350073add to have the same sentence structure in [english](https://github.com/SFML/SFML-Website/pull/161/commits/6570978b2d754dbe76f2dbed93e75e5350073add#diff-eb72bbc81e6c606166b7a488476351a6c24df3c1f1024f338c78eda5d15f4b26R168) and [french](https://github.com/SFML/SFML-Website/commit/6570978b2d754dbe76f2dbed93e75e5350073add#diff-f322d79dc4b9ae639b03bf52e916efba20a39ed02c5161bbcb99772ba6c05e9aR179).

**Comment by kimci86** [comment]
Suggestions:
- Mentioning that `sf::Keyboard::Scancode` is an alias of `sf::Keyboard::Scan::Scancode` in inputs tutorial so that the code example is consistent with the corresponding paragraph.
- Updating the french translation for this change https://github.com/SFML/SFML-Website/pull/161/commits/6570978b2d754dbe76f2dbed93e75e5350073add to have the same sentence structure in [english](https://github.com/SFML/SFML-Website/pull/161/commits/6570978b2d754dbe76f2dbed93e75e5350073add#diff-eb72bbc81e6c606166b7a488476351a6c24df3c1f1024f338c78eda5d15f4b26R168) and [french](https://github.com/SFML/SFML-Website/commit/6570978b2d754dbe76f2dbed93e75e5350073add#diff-f322d79dc4b9ae639b03bf52e916efba20a39ed02c5161bbcb99772ba6c05e9aR179).

**Comment by eXpl0it3r** [comment]
> Mentioning that `sf::Keyboard::Scancode` is an alias of `sf::Keyboard::Scan::Scancode` in inputs tutorial so that the code example is consistent with the corresponding paragraph.

Hmmm, I'd lean more to leave it as is, but maybe I underestimation the confusion this can cause. It feels like a very technical thing to explain, plus I want to promote the usage of `sf::Keyboard::Scancode`. 

Any other viewpoints/opinions?

**Comment by kimci86** [comment]
> Hmmm, I'd lean more to leave it as is, but maybe I underestimation the confusion this can cause. It feels like a very technical thing to explain, plus I want to promote the usage of sf::Keyboard::Scancode.

On second thought, I think you are right. A beginner probably doesn't this technical detail.
